"""add langsmith_run_id to analysis_versions

Revision ID: 37f07358b4c4
Revises: 42f82340ba33
Create Date: 2026-07-05 19:48:34.678800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f07358b4c4'
down_revision: Union[str, None] = '42f82340ba33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_versions', sa.Column('langsmith_run_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_versions', 'langsmith_run_id')
    # ### end Alembic commands ###
