"""add applied_hints to analysis_versions

Revision ID: 42f82340ba33
Revises: db12180e63ae
Create Date: 2026-07-05 19:27:54.605392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f82340ba33'
down_revision: Union[str, None] = 'db12180e63ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_versions', sa.Column('applied_hints', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_versions', 'applied_hints')
    # ### end Alembic commands ###
