"""initial schema

Revision ID: 9430f947f480
Revises: 
Create Date: 2026-07-03 23:51:05.303994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9430f947f480'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_audit_log_analysis_id'), 'action_audit_log', ['analysis_id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('rerun_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_incident_id'), 'analysis_reports', ['incident_id'], unique=False)
    op.create_table('analysis_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=False),
    sa.Column('workaround', sa.String(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('sub_reports', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('edited_by', sa.String(), nullable=False),
    sa.Column('edit_source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_versions_analysis_id'), 'analysis_versions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_versions_incident_id'), 'analysis_versions', ['incident_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('suggested_edit', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_analysis_id'), 'chat_history', ['analysis_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('sources_hint', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('per_agent', sa.JSON(), nullable=False),
    sa.Column('total_input', sa.Integer(), nullable=False),
    sa.Column('total_output', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_metrics_analysis_id'), 'token_metrics', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_token_metrics_incident_id'), 'token_metrics', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_metrics_incident_id'), table_name='token_metrics')
    op.drop_index(op.f('ix_token_metrics_analysis_id'), table_name='token_metrics')
    op.drop_table('token_metrics')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_chat_history_analysis_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_analysis_versions_incident_id'), table_name='analysis_versions')
    op.drop_index(op.f('ix_analysis_versions_analysis_id'), table_name='analysis_versions')
    op.drop_table('analysis_versions')
    op.drop_index(op.f('ix_analysis_reports_incident_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_action_audit_log_analysis_id'), table_name='action_audit_log')
    op.drop_table('action_audit_log')
    # ### end Alembic commands ###
