"""add improvement hints table

Revision ID: db12180e63ae
Revises: 9430f947f480
Create Date: 2026-07-05 19:19:16.790736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db12180e63ae'
down_revision: Union[str, None] = '9430f947f480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_hints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('actual_resolution', sa.String(), nullable=False),
    sa.Column('what_it_got_right', sa.String(), nullable=False),
    sa.Column('what_it_missed', sa.String(), nullable=False),
    sa.Column('hint_summary', sa.String(), nullable=False),
    sa.Column('langsmith_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improvement_hints_analysis_id'), 'improvement_hints', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_improvement_hints_incident_id'), 'improvement_hints', ['incident_id'], unique=False)
    op.create_index(op.f('ix_improvement_hints_service'), 'improvement_hints', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_improvement_hints_service'), table_name='improvement_hints')
    op.drop_index(op.f('ix_improvement_hints_incident_id'), table_name='improvement_hints')
    op.drop_index(op.f('ix_improvement_hints_analysis_id'), table_name='improvement_hints')
    op.drop_table('improvement_hints')
    # ### end Alembic commands ###
